# Generated by Django 4.1 on 2024-04-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'node_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PatentData',
            fields=[
                ('id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('序号', models.CharField(blank=True, max_length=255, null=True)),
                ('标题_中文_field', models.CharField(blank=True, db_column='标题 (中文)', max_length=255, null=True)),
                ('标题_英文_field', models.TextField(blank=True, db_column='标题 (英文)', null=True)),
                ('摘要_中文_field', models.TextField(blank=True, db_column='摘要 (中文)', null=True)),
                ('摘要_英文_field', models.TextField(blank=True, db_column='摘要 (英文)', null=True)),
                ('申请人', models.CharField(blank=True, max_length=255, null=True)),
                ('公开_公告_号', models.CharField(blank=True, db_column='公开（公告）号', max_length=255, null=True)),
                ('公开_公告_日', models.CharField(blank=True, db_column='公开（公告）日', max_length=255, null=True)),
                ('申请号', models.CharField(blank=True, max_length=255, null=True)),
                ('申请日', models.CharField(blank=True, max_length=255, null=True)),
                ('公开类型', models.CharField(blank=True, max_length=255, null=True)),
                ('专利类型', models.CharField(blank=True, max_length=255, null=True)),
                ('公开国别', models.CharField(blank=True, max_length=255, null=True)),
                ('链接到incopat', models.CharField(blank=True, max_length=255, null=True)),
                ('dwpi用途', models.TextField(blank=True, null=True)),
                ('dwpi优势', models.TextField(blank=True, null=True)),
                ('dwpi新颖性', models.TextField(blank=True, null=True)),
                ('dwpi详细描述', models.TextField(blank=True, null=True)),
                ('技术摘要', models.TextField(blank=True, null=True)),
                ('中文摘要_技术摘要', models.TextField(blank=True, db_column='中文摘要+技术摘要', null=True)),
            ],
            options={
                'db_table': 'patent_data',
                'managed': True,
            },
        ),
    ]
